### ISSUE TITLE
add postgres as an option for balance tracking

### ISSUE THREAD

**Issue by matdehaast** [interledger/rafiki#1016]
There is a need to have Rafiki configurable to allow just using the Postgres datastore to track the balances.

* Configurable on startup
* Use an interface that can either use TB or Postgres

Issues:
- [x] #1086
- [x] #1087
- [x] #1088
- [x] #1089
- [x] #1090
- [x] #1091
- [x] #1092
- [x] #1093

**Comment by wilsonianb** [comment]
There should be benefits to using postgres in the majority of `backend` tests (including being able to truncate)

**Comment by wilsonianb** [comment]
I'm wondering if this could also replace the connector existing
https://github.com/interledger/rafiki/blob/d05a80d6bbb268a5ec65dad06d79583fba55b785/packages/backend/src/connector/core/test/mocks/accounting-service.ts#L40

**Comment by wilsonianb** [comment]
The connector could benefit from support for single phase transfers
https://github.com/interledger/rafiki/blob/f7017172b576185b37e885c513555c5704a24ceb/packages/backend/src/connector/core/middleware/balance.ts#L78-L79

Not sure if it makes to include as a part of this. Otherwise we should belatedly open an issue for it.
