### ISSUE TITLE
Is it currently possible to test open-payment locally?

### ISSUE THREAD

**Issue by anguschiu1** [interledger/rafiki#1217]
Excuse me, know the team is working the documentation but I am in a bit haste to try out the Open Payment API for our MVP.

But I am unable to install locally via `npm install @interledger/open-payments` with following messages in debug log:

```
1303 verbose cwd /Users/anguschiu/dev/rafiki
1304 verbose Darwin 22.3.0
1305 verbose node v18.14.2
1306 verbose npm  v9.5.0
1307 error Cannot read properties of null (reading 'matches')
1308 verbose exit 1
1309 timing npm Completed in 5105ms
```

`/Users/anguschiu/dev/rafiki` is the path of cloned repo. Have I done something wrong (like Node or NPM version, path, etc), or I just need to wait? 

Thank you!

**Comment by mkurapov** [comment]
Hi @anguschiu1, thank you for opening up the issue!

I'm currently [working](https://github.com/interledger/rafiki/issues/1195) on publishing the packages we have in Rafiki to npm, so at the moment, they are still unpublished. They should be deployed very soon, and I can let you know when I've done so.

In the meantime, since you've forked Rafiki, (and I'm assuming working on a project as a sibling package to the other ones in the repository) you can actually just link to `open-payments` using the workspace protocol, similarly to how `backend` imports `open-payments`:

https://github.com/interledger/rafiki/blob/dbdf55536dc6a93a824fd6078fc9212a1e879b9f/packages/backend/package.json#L79

Small caveat here, make sure to build the package first before building the rest of your project, (similarly to `backend`):
https://github.com/interledger/rafiki/blob/dbdf55536dc6a93a824fd6078fc9212a1e879b9f/packages/backend/package.json#L7-L8

Also, I'm nearly ready to publish some [documentation](https://github.com/interledger/rafiki/pull/1207) for the library, but before it gets to `main`, you can take a look at WIP docs [here](https://github.com/interledger/rafiki/tree/970/mk/docs-open-payments/packages/open-payments).
