### ISSUE TITLE
Add GraphQL query to fetch list of payments

### ISSUE THREAD

**Issue by raducristianpopa** [interledger/rafiki#1502]
In order to display all the payments (incoming and outgoing) in the Admin UI, we need a unified query that has the ability to paginate over all of them.

**Comment by BlairCurrey** [comment]
I've been trying to scope this out. This will take some changes to the db. We can't simply combine incoming/outgoing page results together (results would be wrong, we would have 2 cursors, and front end can already do this anyways). I see a few options which I dont have a strong preference on at the moment:

- a new `combinedPaymentsView`. This view is basically a stored query to combine all the payments via a `UNION ALL` of incoming and outgoing (with new field specfying incoming/outgoing). The union will happen whenever the view is used so it's more expensive to read from than a table that just has them all combined, but it is a direct extension of our current schema.
  - slight variation on this is a materialized view which I don't think we want because it trades some payment read-heaviness for write-heaviness and adds some complexity with managing refreshing the view

- refactor `incomingPayments`, `outgoingPayments` tables to inherit from a new parent `payments` table. The parent table would have the columns common to both tables and the child tables would have the non-shared columns. You can read/write to the child tables as we currently do but then we can also read from the parent table to get all of them without doing a `UNION ALL` every time. However, the parent records would not have the non-shared columns (such as `incomingPayment.incomingAmountValue`) which we probably want. In which case we need to `JOIN` which probably mitigates that advantage. 

With either of these we can make a combined payments model using the view/parent table which we can then use our existing `getPage` method on.

Initially I prefered the new parent `payments` table with inheritance until realizing we'd likely need to join against the child tables. Performance-wise I'm not sure there is any meaningful difference, and its probably pre-mature to focus on that anyways. The table inheritance change would be a bit more complicated, although I think it does express a natural relationship between the data.

**Comment by BlairCurrey** [comment]
Some other details shared by Radu in our conversation:

This wil powering a list of payments which should only display the shared fields and they should be filterable by payment pointer and type (incoming or outgoing). From there you can navigate to the individual items which could then use the existing incoming/outcoming resolvers for more details.

Sorting was also discussed but was left out of this as it hasn't been implemented anywhere yet and I wasn't sure what that would take or how complicated that would be in combination with our pagination logic (which controls the sort order in places).
