### ISSUE TITLE
Add Mermaid support to documentation

### ISSUE THREAD

**Issue by huijing** [interledger/rafiki#1773]
We would like to add Mermaid support to the Rafiki docs, currently running on Starlight.

**Comment by huijing** [comment]
We have unfortunately run into a blocker where the generated SVG has issues with attributes that contain dashes, e.g. `marker-end` is being generated as `markerend` causing the arrow heads to not render.
Am currently in the process of asking for help (https://github.com/remcohaszing/remark-mermaidjs/issues/23), will continue to update this issue if it progresses.

**Comment by BlairCurrey** [comment]
I was testing this out and found a few things.

- The arrows in the mermaid diagram in `grant-interaction.mdx` renders if you change it to the `.md` extension. I assume we need the JSX stuff though so I'm not sure that's a solution. I noticed this after seeing that the event-handlers page renders arrows just fine: http://localhost:1101/integration/event-handlers/. I thought maybe we need to add the mdx integration but it fails to parse the mdx files after installing (and it currently seems to read mdx fine anyways). Not sure why. https://docs.astro.build/en/guides/markdown-content/#mdx-only-features 
- logging out the SVG from the `remarkMermaid` transformer shows that it returns a good svg with `marker-end`. Seems like its astro mangling it somewhere.
- When I look in the build folder, `marker-end` is actually `markerEnd` (then `markerend` in the browser because [html attributes are case-insensitive](https://html.spec.whatwg.org/multipage/dom.html#case-insensitivity)). It seems like there is some logic in astro for turning kebab-case to camelCase but none of it sticks out as a likely culprit: https://github.com/search?q=repo%3Awithastro%2Fastro%20camel&type=code

**Comment by huijing** [comment]
This issue is not entirely solved, but we do have Mermaid support in .md files with the ```mermaid syntax. It does not work in .mdx yet. So leaving this open for now.

**Comment by huijing** [comment]
This has been resolved by https://github.com/interledger/rafiki/pull/2237
