### ISSUE TITLE
Automatically bump `package.json` Rafiki version when releasing new package

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#1946]
## Context
When we release a new version of Rafiki, we should automatically bump `package.json` in the root folder, similar to how 
- https://github.com/interledger/rafiki/pull/1945 

is done manually.

### EDIT:
A bump in package.json is a new commit that should not happen after we tag. Hence, what we really need is a workflow that detects that package.json has seen a version bump and then automatically tags on push to main.

**Comment by anurag629** [comment]
@sabineschaller @mkurapov Please assign me this issue

**Comment by nayaldivya** [comment]
Hey! Can I take this up?

**Comment by sabineschaller** [comment]
@anurag629 @nayaldivya the PR we have on this already, created by @error9098x, has stagnated. We came to the conclusion that the proposed flow does not work since the change in the package.json is another commit and cannot happen after we tagged. That's why I proposed to have a flow that automatically tags main if the commit changes the version in package.json.

**Comment by mkurapov** [comment]
@sabineschaller let's close this if we are going to just remove `version` from `package.json`?
