### ISSUE TITLE
Webhooks spec missing event schema

### ISSUE THREAD

**Issue by brad-dow** [interledger/rafiki#2920]
In reviewing the [webhooks spec](https://github.com/interledger/rafiki/blob/main/packages/backend/src/openapi/specs/webhooks.yaml), I noticed that it was missing the following:

- Missing `incomingPaymentCreated` event
- Missing `amount` schema defined (several properties reference it)

**Comment by mkurapov** [comment]
@brad-dow 

> Missing `amount` schema defined (several properties reference it)

The schema isn't missing the `amount` field per se, it's linked from the Open Payments resource server schema which we pull in programmatically from the open-payments package. It could easily be standalone though, we just need to write out the full amount schema (not too bad).

Just a note: for this webhook spec, it's easy to remove the dependency on the OP resource server spec, but will be a different story for the IDP spec since we import a lot more from the OP auth server spec.

**Comment by mkurapov** [comment]
@oana-lolea maybe for now, we can just add the `amount` schema in the spec directly (without referencing the other spec). Since its just one object with three fields that I don't suppose would change, I'm not worried about diverging from the Open Payments specs.
