### ISSUE TITLE
docs: create peering integration doc

### ISSUE THREAD

**Issue by melissahenderson** [interledger/rafiki#2967]
This comes out of the Rafiki work week. Create a peering setup page for the integration docs. The outline is roughly "add asset", "add peer", "create wallet address". However, there needs to be a larger discussion around what we want to include in the docs before any work starts on this. We also have peering information in various places in the published docs.

**Comment by brad-dow** [comment]
Working doc with notes here: https://docs.google.com/document/d/1unZlt-cW5qIbmp65yajVz49Ctlj0oQuKGyadjatk1SY/edit?tab=t.0#heading=h.x5dv83b5t1jd

**Comment by brad-dow** [comment]
PR for this one https://github.com/interledger/rafiki/pull/3166

A note about the content that I don't want to forget:
I removed each of the subsections that link to the Rafiki Admin guide. I know all of the other requirements pages have it broken down by API or Rafiki Admin. Take the [Assets page](https://rafiki.dev/integration/requirements/assets/) for example. There's a section for "Add an asset using the `CreateAsset` GraphQL mutation" and a section for "Add an asset using Rafiki Admin".

Because the peering integration guide has so many sections (Add asset, add peer, add wallet address, edit peer, delete peer), it just felt heavy to replicate the same format as the other pages - say a few words and link to the admin guide for each and every operation. 

We can talk about this as a group but I see a few options here...we can either:
- Add those sections back into the peering integration guide
- Edit the other requirements pages to follow this pattern
- Or they can just be different

**Comment by brad-dow** [comment]
Another quick note:
I made it clear in the peering integration guide that setting up peering is optional unless you want to participate in transactions with another ASE running Rafiki. However, I didn't change the [Overview and checklist page](https://rafiki.dev/integration/requirements/overview/) to include peering. If we wanted to add it in but make a note about it not _technically_ being a requirement, we could slide it in between "Support at least one asset" and "Associate each user-facing payment account with a wallet address".

**Comment by melissahenderson** [comment]
I'm going to make two new issues in GitHub--one for admin guide references and one for updates to the Overview and Checklist page. 

Admin Guide references: Going off one of your suggestions, I think we should remove the stand-alone Admin Guide section and instead include mention of it in the page's overview. 

Overview and Checklist page: There's actually a few things that are optional, but they aren't called in an obvious way. We'll fix that and include peering.
