### ISSUE TITLE
Enable exactOptionalPropertyTypes

### ISSUE THREAD

**Issue by wilsonianb** [interledger/rafiki#594]
https://github.com/interledger/rafiki/pull/591#discussion_r965984590

https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes
Update Typescript to 4.4.0+
Enable [`strictNullChecks`](https://www.typescriptlang.org/tsconfig#strictNullChecks):
```
error TS5052: Option 'exactOptionalPropertyTypes' cannot be specified without specifying option 'strictNullChecks'.
```

**Comment by BlairCurrey** [comment]
I started on this and had some questions (more context for these below):
- Do we still want to do this?
- If so, it will impact code style quite a bit - do people have a preference for how we handle this new rule? Explicitly including undefined on optional types vs. explicitly checking values before adding undefined properties to objects?
- @sabineschaller , did you run into any specific problems? I see this was started/stopped twice previously.

### More context for these questions:

I tend to think this rule is good in principle because it forces us to think more intentionally about the difference between a property not existing on an object and it not being defined. This is often but not always equivalent so not observing the difference could lead to bugs. This setting requires the "strict" setting but is not enabled under strict by default. My understanding is that its not enabled by default because it breaks so many things, not because it's not recommended. 

However, after digging into it I'm starting to have some concerns about enabling it.

1. Invasive - lots of code changes required. Either extra code to check if properties are undefined, or widening optional properties to explicitly include `undefined` ([elaborated on in the body of my draft PR](https://github.com/interledger/rafiki/pull/2348)). This isn't a bad thing, I just want to make sure we get the direction right since it will require many changes.
    - I kinda view adding `undefined` to the type as a shortcut to get things working with the ideal being to not add undefined properties to an object. Perhaps the "shortcut" will be appropriate in some cases where an interface has lots of optional properties and is widely used.
2. Prescriptive style change. Kinda goes against some normal assumptions about how to write typescript/javascript. Especially if we opt for explicitly checking for undefined before assigning properties instead of widening optional properties to include `undefined` - it creates a lot of extra code in some places. So not sure how people will feel about that.
3. Potentially complicated by libraries and generated types. May or may not have workarounds for every case (or workarounds may required some more complicated TS). Wondering if this had anything to do with the stopping the previous efforts?
    - For example, [needing to wrap all the generated resolver function types with `NonNullable` here because the generated type is optional](https://github.com/interledger/rafiki/pull/2348/files#diff-2986eba70f3533955dd4e98091c92028208bb9a1208f7c3f753efe8282ebf8f0). This case is not so bad, but I wonder if there will be similar that are not so easily fixed.

**Comment by sabineschaller** [comment]
@BlairCurrey 
I don't remember the advantage from turning this on. I wish I could ask @wilsonianb now 😜
I'm ok with dropping this for now and reopening it if we find a reason to include it.

**Comment by BlairCurrey** [comment]
> @BlairCurrey I don't remember the advantage from turning this on. I wish I could ask @wilsonianb now 😜 I'm ok with dropping this for now and reopening it if we find a reason to include it.

Looks like it comes from here where he wanted to differentiate between null and 
 non-existent properties in an open payments response: https://github.com/interledger/rafiki/pull/591#discussion_r965984590 I guess even in that case we could only set that key on the object conditionally, instead of inlining as `null`/`undefined` with or without the rule. I guess the rule is meant to force that. I don't necessarily disagree with the rule because the whole `undefined` vs not defined is a total javascript foot gun but  not only are the required changes extensive (and potentially problematic w/ generated or npm package types) but it kinda forces a large coding style change (or explicitly widening optional property types to skirt the rule) that I'm not sure everyone would agree. I'll drop it for now and close my draft pr but leave the branch up for reference.

**Comment by sabineschaller** [comment]
Yeah, it had to do with JSON using type `null` but not `undefined`
