### ISSUE TITLE
Assign LiquidityAccountType for all liquidity accounts

### ISSUE THREAD

**Issue by wilsonianb** [interledger/rafiki#605]
https://github.com/interledger/rafiki/blob/main/packages/backend/src/accounting/service.ts#L23-L30

**Comment by sabineschaller** [comment]
Can you please elaborate on this?

**Comment by wilsonianb** [comment]
Previously, we weren't assigning an account code in TigerBeetle for Rafiki liquidity accounts
https://github.com/tigerbeetledb/tigerbeetle/blob/main/docs/DESIGN.md#data-structures

I think this was resolved by
- https://github.com/interledger/rafiki/pull/1057
- https://github.com/interledger/rafiki/pull/1057/commits/9c5fa41792fd5a4e6b6136b118a110b6e3f61364

I'll let @mkurapov confirm

**Comment by mkurapov** [comment]
Yes, since `accountType` is now required during liquidity account creation:
https://github.com/interledger/rafiki/blob/a27c1ea4a382182cb6191684d8ebe87c2426129f/packages/backend/src/accounting/service.ts#L49-L54 all TigerBeetle accounts should have a corresponding "TigerbeetleAccountCode":
https://github.com/interledger/rafiki/blob/a27c1ea4a382182cb6191684d8ebe87c2426129f/packages/backend/src/accounting/tigerbeetle/service.ts#L39-L48
