### ISSUE TITLE
Make sig validation not processed in dev mode

### ISSUE THREAD

**Issue by matdehaast** [interledger/rafiki#664]
If a user sets the `Config.env = "dev"` we should disable signature validation for incoming requests on the AS and the RS. For the AS we can remove the current mechanism we use to do that and rather just assume it from the mode.

This will make it initially much easier to work with Postman as we still need to add signature support to it

**Comment by mkurapov** [comment]
@matdehaast wanted to add more context here.

I believe the current mechanism actually lives on the RS, since on an Open Payments requests you can just set `authorization: GNAP dev-access-token`, and it'll skip through the actual signature verification: 

https://github.com/interledger/rafiki/blob/main/packages/backend/src/open_payments/auth/middleware.ts#L30

However, what's a bit tricky here though is the fact that you can bypass sig verification, you still need to have `signature` and `signature-input` variables in the header (even if they are blank) as that checking is done inside the OpenAPI validation:

https://github.com/interledger/rafiki/blob/main/packages/backend/src/app.ts#L339

I don't believe there is anything to bypass signature validation on the AS side, however.

**Comment by mankins** [comment]
Ok, my dev problems were fixed, so I was able to run these tests locally and make some changes.

I'd love to some feedback to see if the approach is right and worth continuing to do the same thing for RS or if there's some other better way to do this.

**Comment by mkurapov** [comment]
@mankins This is a good approach, I was just clarifying previously that the existing mechanism (with the `dev-access-token`) lives on the resource server side and not originally on the authorization server side. 

I can take a look at the PR later tonight, and do some own testing too.

**Comment by wilsonianb** [comment]
`dev-access-token` helps the RS skip HTTP signature validation on client-RS requests.
#683 will help the AS skip HTTP signature validation on client-AS requests.

**Comment by wilsonianb** [comment]
resolved by:
- https://github.com/interledger/rafiki/pull/683 / https://github.com/interledger/rafiki/pull/735
- https://github.com/interledger/rafiki/pull/741
