### ISSUE TITLE
Add deposit and withdrawal lookup

### ISSUE THREAD

**Issue by wilsonianb** [interledger/rafiki#68]
In order to support `getDeposit` and `getWithdrawal` graphql queries, the accounts service needs to be able to look up deposits and withdrawals by id.
Currently the id is the tigerbeetle transfer id.
Lookup would require either:
- adding a transaction and/or deposit and/or withdrawal postgres tables
- [tigerbeetle transfer lookup](https://github.com/coilhq/tigerbeetle/issues/28) + postgres account table index by balance id

**Comment by jorangreef** [comment]
@wilsonianb we've started on adding indexes and then full querying to TigerBeetle.

 It'll be a few weeks out though, so we can also add temporary support for transfer queries by id to TB in the interim, which is quite a quick feature, just so that you don't need to duplicate transactions out to PG.

**Comment by wilsonianb** [comment]
@jorangreef Thanks for the update.
We haven't and likely won't take any steps toward storing transactions in postgres.
With the likely upcoming changes to how rafiki handles accounts, I can't promise that we'll be chomping at the bit to take advantage of temporary transfer query support.

**Comment by wilsonianb** [comment]
- https://github.com/coilhq/tigerbeetle-node/pull/21 has been merged and appears to provide the functionality needed for this task

**Comment by wilsonianb** [comment]
Will track in:
- #74 
- #75
