### ISSUE TITLE
Throw an error when an invalid `transfer.id` is provided for `accounting/transfers.ts#createTransfers()`

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#965]

**Comment by wilsonianb** [comment]
Maybe we change `CreateTransferOptions` to be a union type for creating new, committed, or voided transfers:
https://github.com/interledger/rafiki/blob/dc909a6e73aec9064fd144b0a79fa74aceb07c88/packages/backend/src/accounting/transfers.ts#L19-L31

**Comment by wilsonianb** [comment]
actually, what is an invalid `transfer.id`?
This currently throws
https://github.com/interledger/rafiki/blob/dd07d2ff6f157c8b3fd671e9d74f7ea86e91ee5b/packages/backend/src/accounting/transfers.ts#L57
https://github.com/interledger/rafiki/blob/dd07d2ff6f157c8b3fd671e9d74f7ea86e91ee5b/packages/backend/src/accounting/utils.ts#L5-L13

**Comment by koekiebox** [comment]
@wilsonianb @sabineschaller I had a look at the logic. 

It has been some time since I looked at the code. :-) With regards to the `toTigerbeetleId` function, I believe we are covered and this issue may be closed.
I see the following PR ensures that the id is valid:
https://github.com/interledger/rafiki/commit/2f8e82a1c91b0d2c4ff554b0851947351d6afa03

But I remember another issue where in some cases the account id was a `number` and not `bigint`. 
If I remember correctly, it was during an internal lookup where the type wasn't always a `bigint`. 
Sorry, I will have a look at where I have noted it, I remember discussing it with you @wilsonianb , do you perhaps recall the conversation?

**Comment by wilsonianb** [comment]
>But I remember another issue where in some cases the account id was a number and not bigint.

@koekiebox That rings a bell. I'll take another look. Thanks

**Comment by wilsonianb** [comment]
I still haven't found an error case not covered by `toTigerbeetleId`
Closing for now
